### PR TITLE
Gem guide improvements

### PR DESCRIPTION
**Pull request by EduardoBautista**
Just trying to bring the guide up to date.

### CODE REVIEW

**Comment by radar** [comment]
LGTM. Is there more to go on this PR?

**Comment by EduardoBautista** [comment]
All that I could come up with.  Unless you or someone else can think of something else that could be updated.

**Comment by radar** [comment]
Not at the moment :)

**Comment by radar** [comment]
You might want to have another PR for updating the code in `gem-scaffold/foodie`

**Comment by EduardoBautista** [comment]
@radar Ah yes!

**Pull request merged**
